config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :test_interventions
  resources :agendas
  devise_for :users
  get 'users/', to: 'users#index'
  get 'test_interventions/', to: 'test_interventions#show'

  root to: "application#index"
end

app/models/test_intervention.rb
class TestIntervention
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  field :title, type: String
  field :image_data, type: String
  include ImageUploader::Attachment.new(:image)

  field :address, type: String
  field :bat, type: String
  field :photo, type: String
  field :orientation, type: String 
  field :state, type: String, default:'en attente'
  field :raison, type: String
  belongs_to :user
  has_one :agenda, autobuild: true, autosave: true
end

app/controllers/test_interventions_controller.rb
class TestInterventionsController < ApplicationController
  before_action :set_test_intervention, only: [:show, :edit, :update, :destroy]

  # GET /test_interventions
  # GET /test_interventions.json
  def index
    if admin_signed_in?
      @test_interventions = TestIntervention.all
    else
    @test_interventions = TestIntervention.where(:user => current_user)
      end
  end

  # GET /test_interventions/1
  # GET /test_interventions/1.json
  def show
    @interventions = TestIntervention.all
  end

  # GET /test_interventions/new
  def new
    @test_intervention = TestIntervention.new
  end

  # GET /test_interventions/1/edit
  def edit
  end

  # POST /test_interventions
  # POST /test_interventions.json
  def create
    @test_intervention = TestIntervention.new(test_intervention_params)

    @test_intervention.user = current_user
    respond_to do |format|
      if @test_intervention.save
        format.html { redirect_to @test_intervention, notice: 'Test intervention was successfully created.' }
        format.json { render :show, status: :created, location: @test_intervention }
      else
        format.html { render :new }
        format.json { render json: @test_intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_interventions/1
  # PATCH/PUT /test_interventions/1.json
  def update
    respond_to do |format|
      if test_intervention_params[:state] == "accepter" && @test_intervention.state != "accepter"
        @test_intervention.agenda = AgendasController.next_agenda
      end
      if @test_intervention.update(test_intervention_params)
        format.html { redirect_to @test_intervention, notice: 'Test intervention was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_intervention }
      else
        format.html { render :edit }
        format.json { render json: @test_intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_interventions/1
  # DELETE /test_interventions/1.json
  def destroy
    @test_intervention.destroy
    respond_to do |format|
      format.html { redirect_to test_interventions_url, notice: 'Test intervention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_intervention
      @test_intervention = TestIntervention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_intervention_params
      params.require(:test_intervention).permit(:address, :bat, :image, :orientation, :state, :raison, :startdate, :endate)
    end
end

app/helpers/test_interventions_helper.rb
module TestInterventionsHelper
end

app/views/test_interventions/_form.html.erb
<%= form_with(model: test_intervention, local: true) do |form| %>
  <% if test_intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_intervention.errors.count, "error") %> prohibited this test_intervention from being saved:</h2>

      <ul>
      <% test_intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :address, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :address, class: "form-control col-sm-4" %>
  </div>

  <div class="form-group row">
    <%= form.label :bat, class:"col-sm-2 col-form-label"%>
    <%= form.text_field :bat, class: "form-control col-sm-4" %>
  </div>

  <div class="form-group row">
    <%= form.label :orientation, class:"col-sm-2 col-form-label"%>
    <%= form.select :orientation, options_for_select([['nord'], ['sud'], ['est'], ['ouest'], ['nord_est'], ['nord_ouest'], ['nord_est_est'], ['nord_nord_est'], ['nord_ouest_ouest'], ['nord_nord_ouest'], ['sud_sud_est'], ['sud_est_est'], ['sud_sud_ouest'], ['sud_ouest_ouest']]),
    include_blank: true, class: "form-control col-sm-4" %>
  </div>
  <div class="form-group row">
  <%= form.label :image, class:"col-sm-2 col-form-label" %>
  <%= form.file_field :image, class:"upload-preview form-control col-sm-4" %>
  </div>

  <div class="form-group row">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/test_interventions/edit.html.erb
<h1>Editing Test Intervention</h1>
<%= form_with(model: @test_intervention, local: true) do |form| %>
    <% if @test_intervention.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(test_intervention.errors.count, "error") %> prohibited this test_intervention from being saved:</h2>
  
        <ul>
        <% test_intervention.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>
  
    <div class="field">
      <%= form.label :bat %>
      <%= form.text_field :bat %>
    </div>

  
    <div class="field">
      <%= form.label :orientation %>
      <%= form.select :orientation, options_for_select([['nord'], ['sud'], ['est'], ['ouest'], ['nord_est'], ['nord_ouest'], ['nord_est_est'], ['nord_nord_est'], ['nord_ouest_ouest'], ['nord_nord_ouest'], ['sud_est'], ['sud_ouest'], ['sud_sud_est'], ['sud_est_est'], ['sud_sud_ouest'], ['sud_ouest_ouest']],selected: @test_intervention.orientation || nil),
      include_blank: true, class:'form-control m-b' %>
    </div>

  <%if admin_signed_in? %>
      <div class="field" >
      <%= form.label :state %>
      <%= form.select :state, options_for_select([['en attente'], ['en cours'], ['finis'], ['refuser']],selected: @test_intervention.state),
      include_blank: true, class:'form-control m-b' %>
    </div>

    <div class="field">
    <%= form.label :raison %>
    <%= form.text_field :raison %>
  </div>
  <%end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image%>
  </div>

    
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  
<%= link_to 'Show', @test_intervention %> |
<%= link_to 'Back', test_interventions_path %>

app/views/test_interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Interventions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <% if admin_signed_in? %>
      <th scope="col">user</th>
      <% end %>
      <th scope="col">Address</th>
      <th scope="col">Bat</th>
      <th scope="col">Orientation</th>
      <th scope="col">Photo</th>
      <th scope="col">State</th>
      <th scope="col">Raison</th>
      <th scope="col">Startdate</th>
      <th scope="col">Endate</th>

      <th colspan="3">action</th>
    </tr>
  </thead>

  <tbody>
    <% @test_interventions.each do |test_intervention| %>
      <tr>
        <% if admin_signed_in? %>
        <td ><%= test_intervention.user.email %></td>
          <% end %>
        <td><%= test_intervention.address %></td>
        <td><%= test_intervention.bat %></td>
        <td><%= test_intervention.orientation %></td>
        <%if test_intervention.image_url(:small) != nil %>
        <td><%= image_tag test_intervention.image_url(:small) %> </td>
        <%end %>
        <td><%= test_intervention.state %></td>

          <td><%if test_intervention.state == "refusé" %><%= test_intervention.raison %><% end %></td>



          <td> <%if test_intervention.state == "accepter" %><%= test_intervention.agenda[:start] %><% end %></td>
          <td> <%if test_intervention.state == "accepter" %><%= test_intervention.agenda[:end] %><% end %></td>


        <td><%= link_to 'Show', test_intervention %></td>
        <td>
          <%if test_intervention.state == "en attente" or admin_signed_in?%>
          <%= link_to 'Edit', edit_test_intervention_path(test_intervention) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Intervention', new_test_intervention_path %>

app/views/test_interventions/new.html.erb
<h1>New Test Intervention</h1>

<%= render 'form', test_intervention: @test_intervention %>

<%= link_to 'Back', test_interventions_path %>

app/views/test_interventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @test_intervention.address %>
</p>

<p>
  <strong>Bat:</strong>
  <%= @test_intervention.bat %>
</p>
<p>
  <strong>Orientation:</strong>
  <%= @test_intervention.orientation %>
</p>

<p>
  <strong>State:</strong>
  <%= @test_intervention.state %>
</p>

<p>
  <strong>Raison:</strong>
  <%= @test_intervention.raison %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @test_intervention.agenda[:start] %>
</p>

<p>
  <strong>Endate:</strong>
  <%= @test_intervention.agenda[:end] %>
</p>

<div>
  <%= image_tag @test_intervention.image_url(:large) %>
  <!--%= link_to @test_intervention.image_url %-->
</div>

<%= link_to 'Back', test_interventions_path %>