config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :test_interventions
  resources :agendas
  devise_for :users
  get 'users/', to: 'users#index'
  get 'test_interventions/', to: 'test_interventions#show'

  root to: "application#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5Mongoid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">BOB Le Bricoleur</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" routerLink="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <% unless user_signed_in? or admin_signed_in? %>
          <li class="nav-item" >
            <%= link_to 'Sign in', new_user_session_path, {:class=> "nav-link"}%>
          </li>
          <li class="nav-item" >
            <%= link_to 'Sign up ', new_user_registration_path, {:class=> "nav-link"}%>
          </li>
          <%else %>
          <li class="nav-item">
            <%= link_to 'Create Intervention', new_test_intervention_path, {:class=> "nav-link"}%>
          </li>
          <li class="nav-item">
          <%= link_to 'My Intervention', test_interventions_path, {:class=> "nav-link"}%>
          </li>
          <li class="nav-item" *ngIf="auth.session && auth.session.role == 'admin'">
            <%= link_to 'Mon Agenda', agendas_path, {:class=> "nav-link"}%>
          </li>
          <% end %>
      </ul>
    </div>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->

    <% unless !user_signed_in? %>
        <form  class="form-inline my-2 my-lg-0" (ngSubmit)="logout()">
        <label for="logout">  Welcome <%= current_user.email %> </label>
          <%= link_to 'edit', edit_user_registration_path(@user) , class: "nav-link" %>
        <%= link_to 'logout', destroy_user_session_path, :method => :delete, class: "nav-link" %>
      </form>
    <%else %>
      <form  class="form-inline my-2 my-lg-0">
        <i> You are not authentified </i>
      </form>
    <% end %>
  </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>